# dev
dev/charging-service/apim-config:
  - 'environments/dev/charging-service/apim-config/**'
dev/cross-service/apim-config:
  - 'environments/dev/cross-service/apim-config/**'
dev/customer-service/apim-config:
  - 'environments/dev/customer-service/apim-config/**'
dev/ocpi-service/apim-config:
  - 'environments/dev/ocpi-service/apim-config/**'
dev/public-api/apim-config:
  - 'environments/dev/public-api/apim-config/**'
dev/test/apim-config:
  - 'environments/dev/test/apim-config/**'

# stg
stg/charging-service/apim-config:
  - 'environments/stg/charging-service/apim-config/**'
stg/cross-service/apim-config:
  - 'environments/stg/cross-service/apim-config/**'
stg/customer-service/apim-config:
  - 'environments/stg/customer-service/apim-config/**'
stg/ocpi-service/apim-config:
  - 'environments/stg/ocpi-service/apim-config/**'
stg/public-api/apim-config:
  - 'environments/stg/public-api/apim-config/**'
stg/test/apim-config:
  - 'environments/stg/test/apim-config/**'

# prd
prd/charging-service/apim-config:
  - 'environments/prd/charging-service/apim-config/**'
prd/cross-service/apim-config:
  - 'environments/prd/cross-service/apim-config/**'
prd/customer-service/apim-config:
  - 'environments/prd/customer-service/apim-config/**'
prd/public-api/apim-config:
  - 'environments/prd/public-api/apim-config/**'
prd/test/apim-config:
  - 'environments/prd/test/apim-config/**'
