openapi: 3.0.0
info:
  title: Customer Service STG - V3 Final Test
  version: "1.0.3"
  description: "Staging environment - Final test after JSON fix - Ready for approval workflow"
paths:
  /customers:
    get:
      summary: List customers
      responses:
        '200':
          description: Success
  /customers/{id}:
    get:
      summary: Get customer by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Customer found