openapi: 3.0.0
info:
  title: Customer Service STG - CASE DEBUG TEST
  version: "2.1.0"
  description: "Testing case debugging - STG environment"
paths:
  /customers:
    get:
      summary: List customers
      responses:
        '200':
          description: Success
  /customers/{id}:
    get:
      summary: Get customer by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Customer found