openapi: 3.0.0
info:
  title: Public API PRD - FIXED INPUT HANDLING
  version: "2.4.0"
  description: "Testing fixed environment input handling for both manual and auto workflows"
paths:
  /api:
    get:
      summary: Main API endpoint
      responses:
        '200':
          description: Success
        '500':
          description: Server error
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service healthy