openapi: 3.0.0
info:
  title: Public API PRD - COMPREHENSIVE TEST
  version: "2.0.0"
  description: "Multi-environment comprehensive test - PRD environment"
paths:
  /api:
    get:
      summary: Main API endpoint
      responses:
        '200':
          description: Success
        '500':
          description: Server error
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service healthy