openapi: 3.0.0
info:
  title: Public API PRD - MOCK WORKFLOW TEST
  version: "3.1.0"
  description: "Testing mock workflow with GitHub runners, mock terraform, and Slack notifications"
paths:
  /api:
    get:
      summary: Main API endpoint
      responses:
        '200':
          description: Success
        '500':
          description: Server error
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service healthy