openapi: 3.0.0
info:
  title: Public API PRD - Production Update V2  
  version: "1.0.2"
  description: "Production environment update - Testing approval workflow with proper environment separation"
paths:
  /api:
    get:
      summary: Main API endpoint
      responses:
        '200':
          description: Success
        '500':
          description: Server error
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service healthy