openapi: 3.0.0
info:
  title: Public API PRD - COMPREHENSIVE WORKFLOW TEST
  version: "3.0.0"
  description: "Testing new auto-terraform-cd.yml with proper Slack notifications and approval flow"
paths:
  /api:
    get:
      summary: Main API endpoint
      responses:
        '200':
          description: Success
        '500':
          description: Server error
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service healthy