openapi: 3.0.0
info:
  title: Public API PRD - OUTPUT FORMAT FIXED
  version: "3.3.0"
  description: "Testing workflow with fixed GitHub Actions output format"
paths:
  /api:
    get:
      summary: Main API endpoint
      responses:
        '200':
          description: Success
        '500':
          description: Server error
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service healthy