openapi: 3.0.0
info:
  title: Public API PRD - YAML SYNTAX FIXED
  version: "3.2.0"
  description: "Testing workflow with fixed YAML syntax - should work now!"
paths:
  /api:
    get:
      summary: Main API endpoint
      responses:
        '200':
          description: Success
        '500':
          description: Server error
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service healthy