openapi: 3.0.0
info:
  title: Public API PRD - CASE DEBUG TEST
  version: "2.1.0"
  description: "Testing environment case debugging and Slack notification fix"
paths:
  /api:
    get:
      summary: Main API endpoint
      responses:
        '200':
          description: Success
        '500':
          description: Server error
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service healthy