openapi: 3.0.0
info:
  title: Public API PRD - APPROVAL TEST
  version: "4.0.0"
  description: "Testing terraform-apply jobs with environment approvals in PRD"
paths:
  /api:
    get:
      summary: Main API endpoint
      responses:
        '200':
          description: Success
        '500':
          description: Server error
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service healthy