openapi: 3.0.0
info:
  title: Public API PRD - SECRETS VALIDATION TEST
  version: "2.2.0"
  description: "Testing with confirmed webhook secrets - All secrets now exist!"
paths:
  /api:
    get:
      summary: Main API endpoint
      responses:
        '200':
          description: Success
        '500':
          description: Server error
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service healthy