# Test OpenAPI configuration for STG environment
# COMPREHENSIVE TEST - All environments 

openapi: 3.0.0
info:
  title: Public API STG - COMPREHENSIVE TEST
  description: Multi-environment comprehensive test - STG public API
  version: "2.0.0"
  
servers:
  - url: https://api-stg.greenlane.com/public
    description: Staging environment
    
paths:
  /health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  environment:
                    type: string
                    example: "stg"

# Auto-deploy test: STG environment
# Expected: Should trigger deployment for staging
# Service: public-api