openapi: 3.0.0
info:
  title: EMS Service API - COMPREHENSIVE TEST
  version: "2.0.0"
  description: "Multi-environment comprehensive test - DEV EMS service"
paths:
  /energy:
    get:
      summary: Get energy data
      responses:
        '200':
          description: Success
  /status:
    get:
      summary: Check EMS status
      responses:
        '200':
          description: EMS is operational