openapi: 3.0.0
info:
  title: EMS Service API - CASE DEBUG TEST
  version: "2.1.0"
  description: "Testing case debugging - DEV EMS service"
paths:
  /energy:
    get:
      summary: Get energy data
      responses:
        '200':
          description: Success
  /status:
    get:
      summary: Check EMS status
      responses:
        '200':
          description: EMS is operational