openapi: 3.0.0
info:
  title: Charging Service API - CASE DEBUG TEST
  version: "2.1.0" 
  description: "Testing case debugging - DEV environment"
paths:
  /charge:
    post:
      summary: Create charging session
      responses:
        '200':
          description: Success
        '400':
          description: Bad request