openapi: 3.0.0
info:
  title: Charging Service API - COMPREHENSIVE TEST
  version: "2.0.0"
  description: "Multi-environment comprehensive test - DEV environment"
paths:
  /charge:
    post:
      summary: Create charging session
      responses:
        '200':
          description: Success
        '400':
          description: Bad request