openapi: 3.0.0
info:
  title: Charging Service API - V3 with Approval Test
  version: "1.0.3"
  description: "Testing approval workflow with environment-specific deployments"
paths:
  /charge:
    post:
      summary: Create charging session
      responses:
        '200':
          description: Success
        '400':
          description: Bad request