name: Deploy Infrastructure

on:
  push:
    action:
      - pull_request
    branches:
      - main
    paths:
      - 'environments/**/apim-config/openapi/*.yaml'

  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'environments/**/apim-config/openapi/*.yaml'
      
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - dev
          - stg
          - prd

      service:
        description: 'Service'
        required: true
        type: choice
        options:
          - cross-service
          - charging-service
          - customer-service
          - ems-service
          - ocpi-service
          - frontend
          - public-api
          - partner-api

      config:
        description: 'Configuration'
        required: false
        type: choice
        options:
          - infrastructure
          - apim-config
          - psql-config
          - ad-b2c
          - " "

jobs:
  paths:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      result: ${{ github.event_name == 'workflow_dispatch' && steps.set.outputs.input || steps.filter.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Debug GitHub Context
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Pull request merged: ${{ github.event.pull_request.merged }}"
          echo "Inputs.environment: ${{ inputs.environment }}"
          echo "Inputs.service: ${{ inputs.service }}"
          echo "Inputs.config: ${{ inputs.config }}"

      - name: Filter Paths
        if: github.event_name != 'workflow_dispatch'
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: .github/file-filters.yml

      - name: Debug Path Filter Output
        if: github.event_name != 'workflow_dispatch'
        run: |
          echo "Filter output (changes): ${{ steps.filter.outputs.changes }}"

      - name: Check Changes
        if: github.event_name != 'workflow_dispatch' && steps.filter.outputs.changes == '[]'
        run: echo '::notice::No changes were detected in the tracked folders, skipping terraform CD job'
    
      - name: Set Path
        if: github.event_name == 'workflow_dispatch'
        id: set
        run: echo 'input=["${{ inputs.environment }}/${{ inputs.service }}/${{ inputs.config }}"]' >> $GITHUB_OUTPUT

      - name: Map env to secret
        id: map
        run: |
          case "${{ inputs.environment }}" in
            dev)  echo "webhook=${{ secrets.SLACK_WEBHOOK_URL_DEV }}" >> $GITHUB_OUTPUT ;;
            stg)  echo "webhook=${{ secrets.SLACK_WEBHOOK_URL_STG }}" >> $GITHUB_OUTPUT ;;
            prd)  echo "webhook=${{ secrets.SLACK_WEBHOOK_URL_PRD }}" >> $GITHUB_OUTPUT ;;
          esac
          
  debug-condition:
    name: Debug Condition Inputs
    runs-on: ubuntu-latest
    needs: paths
    steps:
      - name: Print Condition Values
        run: |
          echo "Needs paths result: ${{ needs.paths.outputs.result }}"
          echo "GitHub event: ${{ github.event_name }}"
          echo "Was PR merged? ${{ github.event.pull_request.merged }}"
          echo "Final condition evaluation: ${{ (needs.paths.outputs.result != '[]' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch' }}"

  cd:
    name: Terraform CD
    if: ${{ (needs.paths.outputs.result != '[]' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch' }}
    needs: [paths, debug-condition]
    uses: ./.github/workflows/terraform-cd.yml
    with:
      team: greenlane
      environment: ${{ inputs.environment }}
      paths: ${{ needs.paths.outputs.result }}
      terraform-version: 1.6.3
      region: ${{ inputs.environment == 'dev' && 'eastus2' || 'centralus' }}

  slack-notify:
    name: Slack Notification
    if: always()
    needs: [paths, cd]
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Message
        run: |
          echo "Slack will notify for event ${{ github.event_name }}"
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\":information_source: Deploy workflow finished. Event: *${{ github.event_name }}*, Paths: *${{ needs.paths.outputs.result }}*\"}" \
          "$webhook"
          "${{ steps.map.outputs.webhook }}"