name: Deploy Infrastructure

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'environments/**/apim-config/openapi/*.yaml'
      
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - dev
          - stg
          - prd

      service:
        description: 'Service'
        required: true
        type: choice
        options:
          - cross-service
          - charging-service
          - customer-service
          - ems-service
          - ocpi-service
          - frontend
          - public-api
          - partner-api

      config:
        description: 'Configuration'
        required: false
        type: choice
        options:
          - infrastructure
          - apim-config
          - psql-config
          - ad-b2c
          - " "

jobs:
  paths:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      result: ${{ github.event_name == 'workflow_dispatch' && steps.set.outputs.input || steps.filter.outputs.changes }}
      envname: ${{ steps.set.outputs.env || steps.envmap.outputs.env }}
      webhook: ${{ steps.envmap.outputs.webhook }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Debug GitHub Context
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Pull request merged: ${{ github.event.pull_request.merged }}"
          echo "Inputs.environment: ${{ inputs.environment }}"
          echo "Inputs.service: ${{ inputs.service }}"
          echo "Inputs.config: ${{ inputs.config }}"

      - name: Filter Paths
        if: github.event_name != 'workflow_dispatch'
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: .github/file-filters.yml

      - name: Debug Path Filter Output
        if: github.event_name != 'workflow_dispatch'
        run: |
          echo "Filter output (changes): ${{ steps.filter.outputs.changes }}"

      - name: Check Changes
        if: github.event_name != 'workflow_dispatch' && steps.filter.outputs.changes == '[]'
        run: echo '::notice::No changes were detected in the tracked folders, skipping terraform CD job'
    
      # workflow_dispatch হলে inputs.environment ব্যবহার করবে
      - name: Set Path (manual dispatch)
        if: github.event_name == 'workflow_dispatch'
        id: set
        run: |
          echo 'input=["${{ inputs.environment }}/${{ inputs.service }}/${{ inputs.config }}"]' >> $GITHUB_OUTPUT
          echo "env=${{ inputs.environment }}" >> $GITHUB_OUTPUT

      # PR event হলে path থেকে env বের করবে (যেমন dev/stg/prd)
      - name: Extract Env from Path
        if: github.event_name != 'workflow_dispatch'
        id: envmap
        run: |
          path="${{ fromJson(steps.filter.outputs.changes)[0] }}"
          env=$(echo "$path" | cut -d'/' -f1)
          echo "env=$env" >> $GITHUB_OUTPUT
      
  debug-condition:
    name: Debug Condition Inputs
    runs-on: ubuntu-latest
    needs: paths
    steps:
      - name: Print Condition Values
        run: |
          echo "Needs.paths.result: ${{ needs.paths.outputs.result }}"
          echo "GitHub event: ${{ github.event_name }}"
          echo "Was PR merged? ${{ github.event.pull_request.merged }}"
          echo "Env name: ${{ needs.paths.outputs.envname }}"
          echo "Webhook (masked): ${{ needs.paths.outputs.webhook != '' }}"
          echo "Final condition evaluation: ${{ (needs.paths.outputs.result != '[]' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch' }}"

  cd:
    name: Terraform CD
    if: ${{ (needs.paths.outputs.result != '[]' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch' }}
    needs: [paths, debug-condition]
    uses: ./.github/workflows/terraform-cd.yml
    with:
      team: greenlane
      environment: ${{ needs.paths.outputs.envname }}
      paths: ${{ needs.paths.outputs.result }}
      terraform-version: 1.6.3
      region: ${{ needs.paths.outputs.envname == 'dev' && 'eastus2' || 'centralus' }}
