name: Test Slack Notifications Only

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test (dev/stg/prd)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stg
          - prd

jobs:
  test-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Test Slack Notification
        run: |
          echo "Testing Slack notification for environment: ${{ inputs.environment }}"
          
          # Get webhook URL based on environment
          case "${{ inputs.environment }}" in
            "dev")
              WEBHOOK_URL="${{ secrets.SLACK_WEBHOOK_URL_DEV }}"
              ;;
            "stg") 
              WEBHOOK_URL="${{ secrets.SLACK_WEBHOOK_URL_STG }}"
              ;;
            "prd")
              WEBHOOK_URL="${{ secrets.SLACK_WEBHOOK_URL_PRD }}"
              ;;
          esac
          
          # Send test notification
          curl -X POST -H 'Content-type: application/json' \
            -d '{
              "text": "Waiting for APIM apply approval - ${{ inputs.environment }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn", 
                    "text": "*Environment:* ${{ inputs.environment }}\n*Repository:* ${{ github.repository }}\n*Triggered by:* ${{ github.actor }}\n\nWaiting for APIM apply approval."
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {"type": "plain_text", "text": "View Workflow"},
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }' \
            "$WEBHOOK_URL"
          
          echo "✅ Test notification sent to ${{ inputs.environment }} channel"